export * from './list/list';
export * from './home/home';
export * from './login/login';
export * from './settings/settings';
export * from './info/info';
export * from './licenses/licenses';
export * from './privacypolicy/privacypolicy';
export * from './terms/terms';
export * from './popular/popular';
export * from './message-center/message-center';
export * from './tabs/tabs'
export * from './itinerary/itinerary'